listen:
  port: 4040
  address: 0.0.0.0

namespaces:
  - name: nginx
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_time $upstream_response_time "$http_referer" "$http_user_agent"'
    source_files:
      - /var/log/nginx/access.log
    labels: {}
