listen:
  port: 4040
  address: 0.0.0.0

namespaces:
  - name: nginx
    format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_time'
    source_files:
      - /var/log/nginx/access.log
    labels:
      method: "$request_method"
      status: "$status"
