global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'nginxlog'
    static_configs:
      - targets: ['nginxlog_exporter:4040']
