global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'nginxlog'
    static_configs:
      - targets: ['nginxlog_exporter:4040']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Access cAdvisor metrics endpoint